### ISSUE TITLE
restrict setDimensions

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-tooltip#5]
Do not calculate dimension when the tooltip isn't visible.

**Comment by GeorgMeyer23** [comment]
Still calculating top, left properties even if tooltip is not visible.

**Comment by davleh** [comment]
This has been fixed, position is currently only calculated when entering the trigger with the mouse, shortly before tooltip is shown. But it has to be recalculated on resize and perhaps also on scroll. I will create an issue accordingly.
Edit: Recalculation on resize is not necessary. The tooltip is being hidden on resize. Recalculation on scroll neither, as positioning is relative to the document. The only existing problem is, if a container inside the page is scrolled, the position has to be updated!
